name: SharedDeathCounter
version: 1.0
main: me.sdc.SharedDeathCounter
api-version: 1.21
author: Lee6
description: Shared lives hardcore plugin
commands:
  sdc:
    description: 하드코어 시스템 명령어
    usage: /sdc <deaths|status...>